export const projects = [
  {
    title: 'React Webpage v1',
    description: "This website was built based on React JavaScript framework using HTML and CSS for styling. Design was modeled on modern solutions for web design.",
    image: '/images/web_1.jpg',
    tags: ['React', 'JS', 'HTML', 'CSS'],
    source: '',
    website: '',
    visit: 'https://github.com/kol242/react-website-example-v1',
    id: 0,
  },
  {
    title: 'React Webpage v2',
    description:"Slightly different but still same React based website was built next. Design was modeled on modern solutions for web design.",
    image: '/images/web_2.jpg',
    tags: ['React', 'JS', 'HTML', 'CSS'],
    source: '',
    website: '',
    visit: 'https://github.com/kol242/react-website-example-v2',
    id: 1,
  },
  {
    title: '"EasyBlogs"',
    description:'Web application "EasyBlogs" is an Vue.js app using Firebase as database for storing user data. The app requires basic authentication to allow users creating posts.',
    image: '/images/web_3.jpg',
    tags: ['Vue', 'JS', 'HTML', 'SCSS'],
    source: '',
    website: '',
    visit: 'https://github.com/kol242/vue-app-example',
    id: 2,
  },
  {
    title: '"W&W Manager App"',
    description:'Simple web application where you can manage workplaces and workers by reading, adding, updating and removing them from database. Built with React.js.',
    image: '/images/ww-manager-app.jpg',
    tags: ['Vue', 'JS', 'HTML', 'SCSS'],
    source: '',
    website: '',
    visit: 'https://github.com/kol242/ww-manager-app',
    id: 3,
  },
  {
    title: '"Top Pop App"',
    description:'Simple website displaying top 10 songs currently ranked on Deezer music platform. The app was built with React.js',
    image: '/images/top_pop.jpg',
    tags: ['Vue', 'JS', 'HTML', 'SCSS'],
    source: '',
    visit: 'https://github.com/kol242/top-pop-app/tree/main/top-pop',
    website: 'https://top-pop-app.vercel.app/',
    id: 3,
  }
];